### ISSUE TITLE
What is the lora_alpha used in commonsense_reasoning?

### ISSUE THREAD

**Issue by xiaoshingshing2** [NVlabs/DoRA#13]
Thanks for your great work! 

I notice that you use alpha=64 for r=32 in Llama_7B_Dora.sh. What is the value of alpha when using other settings r=[4,8,16,64]?

Besides, I found that the default micro_batch_size in Llama_7B_Dora.sh is 16 and will cause OOM. Should it be 4 according to the paper?

**Comment by nbasyl** [comment]
Hi,
For the alpha value, we simply set it to twice the rank values, so alpha = [8, 16, 32, 128] for rank = [4, 8, 16, 64].
As for the micro_batch_size, you can set it to any value that fits your GPU; it won't affect the result.

**Comment by xiaoshingshing2** [comment]
Thank you very much
