### ISSUE TITLE
Using LLaMA-3-8b in visual instruction tuning

### ISSUE THREAD

**Issue by enkaranfiles** [NVlabs/DoRA#3]
Hello everyone,

Great work!

Have you tested DoRA performance by using LLaMa-v3-8b in the visual instruction tuning and how can I tested in my setting?

**Comment by nbasyl** [comment]
Hi, thanks for your interest in our work. Unfortunately, the projector weight for llama3 is currently not available in LLaVA. Unless you train the projector yourself, using llama3 within the llava framework is not possible at the moment. For the complete list of supported LLMs by LLaVA, please refer to the following link: [LLaVA Model Zoo](https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md).
