### ISSUE TITLE
OOM when use torch.linalg.norm

### ISSUE THREAD

**Issue by shuishen112** [NVlabs/DoRA#4]
Hi, 

It seems torch.linalg.norm will consume more GPU memory in the forward pass. I will encounter an OOM error when using Dora. My implementation for the forward pass is: 

```
adapted = self.weight + torch.matmul(self.lora_b, self.lora_a) / self.rank
column_norm = adapted.norm(p=2, dim=0, keepdim=True)

norm_adapted = adapted / column_norm
calc_weights = self.magnitue * norm_adapted
return F.linear(x, calc_weights, self.bias)
```

**Comment by nbasyl** [comment]
Hi, your implementation is not correct, please refer to section 4.2 in the paper and the official implementation https://github.com/huggingface/peft/blob/main/src/peft/tuners/lora/layer.py
