### ISSUE TITLE
When will Hugging Face support QDORA?

### ISSUE THREAD

**Issue by 190679163** [NVlabs/DoRA#8]
I'm thrilled that DORA is available on Hugging Face PEFT. When will QDORA be supported as well?

**Comment by nbasyl** [comment]
Hi, thanks for your interest in our work, currently, the Hugging Face PEFT's support for QDoRA still has some bugs, so I recommend using the FSDP/QLoRA for QDoRA which you can refer to my step by step instructions under the QDoRA folder
